opentelemetry-operator:
  manager:
    featureGates: "+operator.autoinstrumentation.multi-instrumentation"
    env:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "service.name=opentelemetry-operator"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  kubeRBACProxy:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

  admissionWebhooks:
    certManager:
      enabled: false
    autoGenerateCert:
      enabled: true
