opentelemetry-operator:
  manager:
    env:
      OTEL_RESOURCE_ATTRIBUTES: "service.name=opentelemetry-operator"
    extraArgs:
      - --enable-multi-instrumentation
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  admissionWebhooks:
    certManager:
      enabled: false
    autoGenerateCert:
      enabled: true
      recreate: true
