apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/higuin01/the-easy-mode-addons
    targetRevision: main
    path: installed-addons/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: prometheus-kube-prometheus-admission
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: prometheus-kube-prometheus-admission
  - group: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-kube-prometheus-admission
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: prometheus-kube-prometheus-admission
