apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-root-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/higuin01/the-easy-mode-addons'
        revision: main
        directories:
          - path: installed-addons/*
          - path: installed-addons/argocd-apps
            exclude: true
  template:
    metadata:
      name: 'addon-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/higuin01/the-easy-mode-addons'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
