apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml

# Actions atualiza apenas esta linha via:
# kustomize edit set image higor01/go-otel-allvvin=higor01/go-otel-allvvin:sha-<commit>
images:
- name: higor01/go-otel-allvvin
  newName: higor01/go-otel-allvvin
  newTag: sha-6c7769b46bedc17556953a115a55cfec318f89f0
